on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Check versions
        run: |
          mvn -v
          java --version
#          ls -lhA ~/.m2 

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11.0.15'
          distribution: 'adopt'
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 11.0.5
          java-distribution: adopt
          maven-version: 3.6.0
      - name: Check versions again
        run: |
          mvn -v
          java --version

      - name: Build application
        run: mvn clean package --projects :${{ inputs.service }} --also-make --batch-mode

      - name: Build and push docker image
        run: docker build . --build-arg JAR_FILE=services/${{ inputs.service }}/target/app.jar -t ${{ inputs.service }}:latest
        
      - name: List images
        run: docker images 